# Generated by Django 5.1.4 on 2025-01-07 15:09

import django.db.models.deletion
import ticket_voucher.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Enviado', 'Enviado'), ('Leido', 'Leido'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado')], default='Enviado', max_length=40)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('datecompleted', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('title', models.CharField(default='No title', max_length=100)),
                ('observation', models.TextField(blank=True, null=True)),
                ('custom_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('client_data', models.JSONField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_voucher_staff', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketVoucherFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileupload', models.FileField(upload_to='ticketsfiles/', validators=[ticket_voucher.models.validate_file_extension])),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('extension', models.CharField(blank=True, max_length=10)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ticket_voucher.ticketvoucher')),
            ],
        ),
    ]
